config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
  resources :books, only:[:index, :show, :create, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only:[:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  # 1つの投稿に対して1いいねしかできないようにする
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # ↓ nameのみをkeysに入れるとemailでsignupができない現象が発生する。
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_back(fallback_location: :back)
  end
  
  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_back(fallback_location: :back)
  end
  
  
  private
  
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @user = User.find(@book.user_id)
  end

  def new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    if @user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      @book.title = nil
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: :back)
  end
  
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: :back)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top 
    if user_signed_in?
      redirect_to user_path(current_user.id)
    end
  end
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: @user.id)
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <div class="alert alert-danger">
          <h2><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h2>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model: @book, local: true do |f| %>
        <div class="form-group">
          <label for="inputTitle">Title</label><br>
          <%= f.text_field :title, autofocus: true, id:"inputTitle", class:"form-controll" %>
        </div>
        <div class="form-group">
          <label for="inputOpinion">Opinion</label><br>
          <%= f.text_area :body, autofocus: true, rows: 3, id:"inputOpinion", class:"form-controll" %>
        </div>
        <%= f.submit "Update Book", class: "btn btn-success mb-3" %>
      <% end %>
      <div class="row px-3">
          <%= link_to "Show", book_path(@book) %>
          <p class="px-1">|</p>
          <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'commons/user_info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= form_with model:@book, url:books_path, local:true do |f| %>
        <label for="inputTitle">Name</label>
        <%= f.text_field :title, id:"inputTitle", class: "mb-2" %>
        <label for="inputBody">Opinion</label>
        <%= f.text_area :body, rows:'3', id:'inputBody' %>
        <%= f.submit "Create Book", class: "btn btn-success mt-1" %>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th colspan="3">Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag  book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", size: '60x60' %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(book), class: "text-danger", method: :delete do %>
                      <i class="fas fa-heart"></i> <%= book.favorites.count %>
                    <% end %>
                  </p>
                <% else %>
                  <p>
                    <%= link_to book_favorites_path(book), class: "text-primary", method: :post do %>
                      <i class="fas fa-heart"></i> <%= book.favorites.count %>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td>
                <p>コメント数: <%= book.book_comments.count %></p>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'commons/user_info', user: @user %>

      <h2 class="mt-3">New book</h2>
      <%= form_with model:Book, url:books_path, local:true do |f| %>
        <label for="inputTitle">Name</label>
        <%= f.text_field :title, id:"inputTitle", class: "mb-2" %>
        <label for="inputBody">Opinion</label>
        <%= f.text_area :body, rows:'3', id:'inputBody' %>
        <%= f.submit "Create Book", class: "btn btn-success mt-1" %>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", size: '60x60' %><br>
                <p class="ml-2"><%= @user.name %></p>
              <% end %>
            </td>
            <td class="pt-3">
              <%= link_to edit_book_path(@book) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td class="pt-3">
              <%= @book.body %>
            </td>
            <td class="pt-3">
              <% if @book.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorites_path(@book), class: "text-danger", method: :delete do %>
                    <i class="fas fa-heart"></i> <%= @book.favorites.count %>
                  <% end %>
                </p>
              <% else %>
                <p>
                  <%= link_to book_favorites_path(@book), class: "text-primary", method: :post do %>
                    <i class="fas fa-heart"></i> <%= @book.favorites.count %>
                  <% end %>
                </p>
              <% end %>
            </td>
            <td>
              <p>コメント数: <%= @book.book_comments.count %></p>
            </td>
            <% if @user == current_user %>
              <td>
                <%= link_to edit_book_path(@book) do %>
                  <button type="button" class="btn btn-success">Edit</button>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(@book), method: :delete, data: { confirm: '本当に削除しますか？' } do %>
                  <button type="button" class="btn btn-danger">Destroy</button>
                <% end %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div class="comments">
        <% @book.book_comments.each do |book_comment| %>
          <table class="table">
            <tbody>
              <tr>
                <td>
                  <%= link_to user_path(book_comment.user) do %>
                    <%= attachment_image_tag book_comment.user, :profile_image, :fill, 60, 60, format: "jpeg", fallback: "no_image.jpg", size: '60x60' %><br>
                    <p class="ml-2"><%= book_comment.user.name %></p>
                  <% end %>
                </td>
                <td>
                  <%= book_comment.comment %>
                </td>
                <td>
                  <% if book_comment.user == current_user %>
                    <%= link_to book_book_comment_path(book_comment.book, book_comment), method: :delete, data: { confirm: '本当に削除しますか？' } do %>
                      <button type="button" class="btn btn-danger">Destroy</button>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
        <% end %>
      </div>
      <div class="new-comment">
        <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
          <%= f.text_area :comment, rows:"5", class: "w-100" %><br>
          <%= f.submit " 送信 " %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/commons/_new_book.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model:book, url:books_path, local:true do |f| %>
  <label for="inputTitle">Name</label>
  <%= f.text_field :title, id:"inputTitle", class: "mb-2" %>
  <label for="inputBody">Opinion</label>
  <%= f.text_area :body, rows:'3', id:'inputBody' %>
  <%= f.submit "Create Book", class: "btn btn-success mt-1" %>
<% end %>

app/views/commons/_user_info.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<%= link_to edit_user_path(user.id) do %>
  <button type="button" class="btn btn-outline-secondary btn-block"><i class="fas fa-user-cog"></i></button>
<% end %>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
    <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
            <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
            <p>you can share and exchange your opinions, inpressions, and emotions</p>
            <p>about various books!</p>
            <div class="btn-wrapper col-10 mx-auto">
                <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3" %>
                <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/1a61be8bf4.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="bg-dark text-white">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container navbar-dark">
          <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to user_path(current_user.id), class: 'nav-link text-white' do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to users_path, class: 'nav-link text-white' do %>
                    <i class="fas fa-users"></i> Users
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to books_path, class: 'nav-link text-white' do %>
                    <i class="fas fa-book-open"></i> Books
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-white' do %>
                    <i class="fas fa-sign-out-alt"></i> logout
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to root_path, class: 'nav-link text-white' do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to home_about_path, class: 'nav-link text-white' do %>
                    <i class="fas fa-link"></i> About
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: 'nav-link text-white' do %>
                    <i class="fas fa-user-plus"></i> sign up
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: 'nav-link text-white' do %>
                    <i class="fas fa-sign-in-alt"></i> login
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mt-3 mb-auto">
      <% if flash[:notice] %>
        <p class="notice"><%= flash[:notice] %></p>
      <% end %>
      <%= yield %>
    </main>
    <footer class="bg-white text-dark mr-auto ml-auto vh-100 mt-4">
      <p>CopyRight Infratop.inc</p>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>User info</h1>
      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <label for="inputName">Name</label><br>
          <%= f.text_field :name, autofocus: true, id:"inputName", class:"form-controll" %>
        </div>
        <div class="form-group">
          <label for="inputImage">Image</label><br>
          <%= f.attachment_field :profile_image, id: "inputImage" %>
        </div>
        <div class="form-group">
          <label for="inputIntroduction">Introduction</label><br>
          <%= f.text_area :introduction, autofocus: true, rows: 3, id: "inputIntroduction", class: "form-controll" %>
        </div>
        <%= f.submit "Update User", class: "btn btn-secondary mb-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'commons/user_info', user: @user %>
      <%= render 'commons/new_book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", size: '60x60' %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= link_to "Show", user_path(user) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'commons/user_info', user: @user %>
      <%= render 'commons/new_book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th colspan="3">Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", size: '60x60' %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(book), class: "text-danger", method: :delete do %>
                      <i class="fas fa-heart"></i> <%= book.favorites.count %>
                    <% end %>
                  </p>
                <% else %>
                  <p>
                    <%= link_to book_favorites_path(book), class: "text-primary", method: :post do %>
                      <i class="fas fa-heart"></i> <%= book.favorites.count %>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td>
                <p>コメント数: <%= book.book_comments.count %></p>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>